### ISSUE TITLE
打开游戏没有加载MOD，主页面左下角也没有ModLoader

### ISSUE THREAD

**Issue by Ark-Two** [DoL-Lyra/Lyra#17]
![QQ图片20231121161455](https://github.com/sakarie9/DOL-CHS-MODS/assets/72326210/da1ba527-9ca1-438a-8413-39c2e6f0c15d)
如图，开机没有显示载入MOD的进度，进入主页面也没有ModLoader
（手机型号：vivo s1 pro）

**Comment by sakarie9** [comment]
用的什么版本的呢

再试试汉化仓库里的能不能加载

**Comment by Ark-Two** [comment]
用的是美化+HP+作弊+bj特写的版本

**Comment by sakarie9** [comment]
https://eltirosto.github.io/Degrees-of-Lewdity-Chinese-Localization/

汉化官方给的这个在线版的两个模式都试试呢
