### ISSUE TITLE
检视皮肤出现Bug

### ISSUE THREAD

**Issue by cathy8107** [DoL-Lyra/Lyra#18]
![IMG_20231126_193405](https://github.com/sakarie9/DOL-CHS-MODS/assets/152067315/c60d5bee-d97c-487c-8e9e-8cb6081792d8)

版本右上角，不知道是什么原因，查看的时候就发现Bug了
载了2.2.1却没有这问题

**Comment by sakarie9** [comment]
请使用非整合汉化版测试是否出现同样问题

**Comment by cathy8107** [comment]
![IMG_20231127_182528](https://github.com/sakarie9/DOL-CHS-MODS/assets/152067315/eb098f32-de5c-4db0-81f8-4994c4eb2407)

请问是这个吗？
如果是，那这个检视时没有bug
