### ISSUE TITLE
任何下載版本都無法顯示圖片

### ISSUE THREAD

**Issue by Guava017** [DoL-Lyra/Lyra#45]
![52D5B80A-B1BD-4E66-A36A-432BFFF4E7B8](https://github.com/user-attachments/assets/d875d538-551a-45dd-a93a-77faf1271234)
![51BBB4DD-1B69-4644-A5EF-A1154D0D54A2](https://github.com/user-attachments/assets/426c1cc0-ff37-4219-92dc-636cba120fa3)
![9FBBA362-D706-4AB8-A3D9-6D3F1E37B671](https://github.com/user-attachments/assets/4dd2d5b6-da5e-4166-b93e-33994152bead)
已確認無載入額外mod

**Comment by lyrae-a** [comment]
iOS吗？

iOS 那种利用其他什么东西直接打开 HTML 文件的方式，不能读到放在同目录的图片文件夹，需要使用 ML 类型的图片 mod
