### ISSUE TITLE
艾弗里約會劇情

### ISSUE THREAD

**Issue by Gularo** [DoL-Lyra/Lyra#46]
![1725648813537](https://github.com/user-attachments/assets/c7110acb-8cc6-4e8c-9029-6537a80c0496)
這邊的選項存在問題，不論怎麼選擇都是同樣的結果

**Comment by Gularo** [comment]
ex:裡面有一段敘述中提到市長喜歡白蘭地，但不管誰選白蘭地，市長都會說這不是他的

**Comment by lyrae-a** [comment]
请使用原版汉化确认问题是否同样存在

这里解决不了游戏本身存在的问题
