### ISSUE TITLE
新版本安装包错误

### ISSUE THREAD

**Issue by ACCREK** [DoL-Lyra/Lyra#48]
新版本0.5.2.8无法安装，下载完安装包报错，所有版本都是
![Screenshot_2024-09-23-01-38-32-788_com blackshark packageinstaller](https://github.com/user-attachments/assets/9e75d3cd-ed9a-4a95-91ae-202bbfccf34f)

**Comment by koocey** [comment]
相同情况![Uploading Screenshot_2024-09-23-02-11-38-319_com.miui.packageinstaller.jpg…]()

**Comment by koocey** [comment]
![Screenshot_2024-09-23-02-11-38-319_com miui packageinstaller](https://github.com/user-attachments/assets/c3ff1038-ad80-4bd0-aa87-173b762f7780)
相同情况

**Comment by lyrae-a** [comment]
b6941f3
