### ISSUE TITLE
大佬，0528最新整合通用战斗贴图错误了

### ISSUE THREAD

**Issue by atd520** [DoL-Lyra/Lyra#49]
![Screenshot_20240923-132603](https://github.com/user-attachments/assets/8102ede1-6dbf-47ac-af58-7f27913c52b4)
![Screenshot_20240923-134736](https://github.com/user-attachments/assets/827e7f65-10d1-4cb1-a16b-8794a55992e0)
都是自愿服务贴图，图二根本没挨打就这样了

**Comment by Ko-Song** [comment]
这是哪个美化?

**Comment by Zed660033** [comment]
https://github.com/Zed660033/mysterious/releases/tag/9.26
