### ISSUE TITLE
更新好版本，版本号没变

### ISSUE THREAD

**Issue by Ko-Song** [DoL-Lyra/Lyra#50]
0.5.2.8版本下载更新后版本依旧显示0.5.1.3![Screenshot_2024-09-25-15-48-34-789_com.vrelnir.DegreesOfLewdity.lyra.jpg](https://github.com/user-attachments/assets/ca9b23a2-1499-4718-9015-90c0edb04df7)

![Screenshot_2024-09-25-15-48-29-972_mark.via.png](https://github.com/user-attachments/assets/6454f0bf-3c3f-4040-984d-486f5694e98f)

**Comment by lyrae-a** [comment]
> 从 v0.5.2.8 开始， DoL 原版修改了打包框架，使得覆盖安装会造成存档丢失。本仓库内的安卓版已修改为新包名，请在旧版导出存档然后在新版中导入。
