### ISSUE TITLE
关于左侧人物动画图像错误，无论电脑端以及安卓端

### ISSUE THREAD

**Issue by ALFANERV** [DoL-Lyra/Lyra#51]
版本为最新的0.528版本，BESC+CSD+BJ特写+WAX，左侧的人物图层在会暴露脱衣的环境下会遮住自己，但是此现象会造成人物的图层错误
![屏幕截图 2024-09-25 181906](https://github.com/user-attachments/assets/e86b5e8e-4269-45a4-8abf-cc82fa87d76a)
![屏幕截图 2024-09-25 181946](https://github.com/user-attachments/assets/f7918756-c2c6-4ff7-a0d8-5299e645029b)
还有更严重的错误
![屏幕截图 2024-09-25 182025](https://github.com/user-attachments/assets/e1404d74-2f92-404f-b7c0-35f0a8eac501)
但是在自己的卧室（即不会暴露的环境）则不会有此错误
![屏幕截图 2024-09-25 182200](https://github.com/user-attachments/assets/0f2f0406-de0d-4454-a56e-3f73a4fe46b2)
但是在自己的卧室发生上述的行为在衣柜的一个选项——“不遮住自己”“遮住自己”都不会使人物发生任何动作

**Comment by ALFANERV** [comment]
貌似只有在线版没有这个问题，没有任何的美化包，估摸着就是代码出问题了

**Comment by lyrae-a** [comment]
美化未适配新版导致的

**Comment by ALFANERV** [comment]
https://github.com/DoL-Lyra/Lyra/issues/51#issuecomment-2376020010
应该是

**Comment by ALFANERV** [comment]
> 原因是游戏源仓库8月31日的一个commit （https://gitgud.io/Vrelnir/degrees-of-lewdity/-/commit/31fcb895af6edc41af6f0832d5a840abf1cf473a） 将路径'img\body'下的'leftarm.png'和'rightarm.png'重命名为了'leftarmcover.png'和'rightarmcover.png'
> 
> 而BES依旧使用原名称
> 
> 我已向BES仓库提交PR （https://gitgud.io/BEEESSS/degrees-of-lewdity-graphics-mod/-/merge_requests/4） ，可手动将路径'img\body'下的'leftarm.png'和'rightarm.png'重命名为'leftarmcover.png'和'rightarmcover.png'来缓解问题

那安卓端怎么解决这个问题？，电脑端好解决，但是安卓端没法这么做

**Comment by travellerse** [comment]
@ALFANERV 我写了一个修复
https://github.com/travellerse/BES-armcover-unofficial-fix/releases/download/v0.1.0/BES-armcover-unofficial-fix.zip  
以mod形式安装即可

**Comment by ALFANERV** [comment]
> 我写了一个修复 https://github.com/travellerse/BES-armcover-unofficial-fix/releases/download/v0.1.0/BES-armcover-unofficial-fix.zip 以mod形式安装即可

啊，安卓端我发现最新的版本已经解决了模型错位的问题，但是我不知道是否真的解决了，所以添加了你回复里的MOD，显示成功然后需要刷心页面生效，我选择了MOD管理界面的重新载入，不太清楚这样做是正确是否让添加的MOD成功（因为我是第一次添加MOD，不清楚正确的方法自己摸索出来的）
