### ISSUE TITLE
镜子-心境-换换心情点击后报错&遮掩身体的贴图出现错误

### ISSUE THREAD

**Issue by SevenHDoll** [DoL-Lyra/Lyra#53]
最新版的BESC+作弊+CSD+BJ特写+WAX与作弊+CSD+SUSATO电脑端整合包均在洗澡结束的画面出现贴图错位，以及susato版本在镜子处多了一个心境选项，但点击后报错
![373330224-24d400dc-370f-4def-9574-ec991c936639](https://github.com/user-attachments/assets/76e6abdf-d228-4a0b-b97e-a2924ff647a0)
![373331447-90431281-3792-44f4-a314-9bee50f21c3c](https://github.com/user-attachments/assets/1d570197-57d8-4666-b8c9-f985f76ef6a9)
![image](https://github.com/user-attachments/assets/f2b75903-f6bb-4154-a5f5-d6e2a7d4ae25)
[degrees-of-lewdity-20241004-000751.txt](https://github.com/user-attachments/files/17281322/degrees-of-lewdity-20241004-000751.txt)
[degrees-of-lewdity-20241003-235758.txt](https://github.com/user-attachments/files/17281325/degrees-of-lewdity-20241003-235758.txt)
[degrees-of-lewdity-20241007-235750.txt](https://github.com/user-attachments/files/17281326/degrees-of-lewdity-20241007-235750.txt)

**Comment by lyrae-a** [comment]
报错可能是 susato 暂未适配的问题

胳膊问题已在 17f8aba 修复，等下次打包发布
