### ISSUE TITLE
关于0.5.2.8安卓端运行着突然出错

### ISSUE THREAD

**Issue by ALFANERV** [DoL-Lyra/Lyra#54]
![Screenshot_20241009_224003_com vrelnir dol lyra](https://github.com/user-attachments/assets/cfefe3d0-e1aa-4628-8141-b7ccd86e1c08)
如图所示，突然就显示出错，说是无法找到对应属性啥的，具体版本是0.5.2.8-5.1.0a-930,BES+作弊+CSD+BJ特写+WAX，我还安装了用户“[travellerse](https://github.com/travellerse)”的修复包《https://github.com/travellerse/BES-armcover-unofficial-fix/releases/download/v0.1.0/BES-armcover-unofficial-fix.zip》，但我移除了安装包MOD也没有解决，还是显示该问题，不太清楚该错误只在.5.2.8的版本出现，或许使用该错误的存档码在其他版本上也会出现问题
[DoL存档码 (2).txt](https://github.com/user-attachments/files/17310446/DoL.2.txt) 这是出问题的版本的存档码

**Comment by ALFANERV** [comment]
哈哈，在摄影棚工作室那里又出错了
![Screenshot_20241010_174958_com vrelnir dol lyra](https://github.com/user-attachments/assets/5209c914-5f76-4b8a-b82c-bdd79098b9fa)

**Comment by lyrae-a** [comment]
![image](https://github.com/user-attachments/assets/e9645d1b-226e-4062-95eb-fc86667f7ec8)

原版问题/存档问题，并非整合问题，请向原版仓库反馈
