### ISSUE TITLE
besc-cheat-csd版本没有了

### ISSUE THREAD

**Issue by 1980219** [DoL-Lyra/Lyra#59]
自从v5.0.6-2.1.0a-0701之后，就没有[BESC+作弊+CSD]的版本了，是因为忘记了？
![e966d13f8794a4c2eb8d600f48f41bd5ac6e3952](https://github.com/user-attachments/assets/dbaa804d-908d-4b95-a393-57fda8aae838)
![d9237e899e510fb3a4b7f0b39f33c895d0430c52](https://github.com/user-attachments/assets/b4396698-5cb7-46d0-8957-9059c29ab049)

**Comment by lyrae-a** [comment]
为了精简版本数，把BESC和WAX绑定了
